<p align="center">
    <img src="https://private-user-images.githubusercontent.com/46355364/238023617-a0f5e7af-d8d6-4ce8-9e71-47376baa35f2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiJrZXkxIiwiZXhwIjoxNjg0MzA5NzExLCJuYmYiOjE2ODQzMDk0MTEsInBhdGgiOiIvNDYzNTUzNjQvMjM4MDIzNjE3LWEwZjVlN2FmLWQ4ZDYtNGNlOC05ZTcxLTQ3Mzc2YmFhMzVmMi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMDUxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzA1MTdUMDc0MzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDMxYWIxOGMxNGIxODI5YzI1MzM3YjdlMmFlZjZmNmZmYWI1YzI0ZGU3MzMxNmY5YTdmNDk0NTZiMmIyZjMzZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.XqGEL9QCAHnnldryiRb7VZ16ERKHspbv3mCXL1-3ABc" alt="Logo">

The Financial Toolkit can take in any dataset which means it works very well with the software from [OpenBB ðŸ¦‹](https://openbb.co/), a leading open-source investment research software platform that gives you access to high-quality financial market data and analytical tools. The mission from OpenBB is to make investment research effective, powerful and accessible to everyone.

OpenBB has the OpenBB SDK and the OpenBB Terminal that both work well with the Financial Toolkit. In this Notebook datasets from the OpenBB SDK are retrieved and loaded into the Financial Toolkit. This demonstrates the ease of use. A similar methodology would work with the OpenBB Terminal in which the export capabilities can be utilised.

To install the **OpenBB SDK** it simply requires the following:

```
pip install openbb --no-cache-dir --upgrade
```

From within Python use:

```python
from openbb_terminal.sdk import openbb
```

For a detailed explanation of how to install and use the OpenBB SDK, please see the official website as found [here](https://my.openbb.co/app/sdk).

In [1]:
from financialtoolkit import Toolkit
from openbb_terminal.sdk import openbb

Much of the functionality that the Financial Toolkit requires, can be found within the `openbb.stocks.fa` module of the OpenBB SDK. For example, when it comes to financial statements from a variety of sources. Within this Notebook the Alpha Vantage source is used to collect data.

First, let's have a look at how the data is depicted when the command `openbb.stocks.fa.balance` is ran.

In [2]:
openbb.stocks.fa.balance("TSLA")

,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Breakdown,,,,
Cash and cash equivalents,22185000.0,17576000.0,19384000.0,6268000.0
Other short-term investments,5932000.0,131000.0,NaN,NaN
Total cash,22185000.0,17707000.0,19384000.0,6268000.0
Net receivables,2952000.0,1913000.0,1886000.0,1324000.0
Inventory,12839000.0,5757000.0,4101000.0,3552000.0
Other current assets,2941000.0,NaN,NaN,NaN
Total current assets,40917000.0,27100000.0,26717000.0,12103000.0
"Gross property, plant and equipment",36635000.0,31176000.0,23375000.0,20199000.0
Accumulated depreciation,-10459000.0,-7918000.0,-6072000.0,-11726000.0
"Net property, plant and equipment",36635000.0,31176000.0,23375000.0,20199000.0
Goodwill,194000.0,200000.0,207000.0,198000.0
Intangible assets,593000.0,1717000.0,313000.0,339000.0
Other long-term assets,4193000.0,2138000.0,1536000.0,1077000.0
Total non-current assets,41421000.0,35031000.0,25431000.0,22206000.0
Total assets,82338000.0,62131000.0,52148000.0,34309000.0
Current debt,1502000.0,1589000.0,2132000.0,1785000.0
Accounts payable,15255000.0,10025000.0,6051000.0,3771000.0
Accrued liabilities,7142000.0,5719000.0,3855000.0,2905000.0
Deferred revenues,2810000.0,2372000.0,2210000.0,1889000.0
Other current liabilities,354000.0,294000.0,241000.0,317000.0
Total current liabilities,26709000.0,19705000.0,14248000.0,10667000.0
Long-term debt,1597000.0,5245000.0,9607000.0,11634000.0
Deferred tax liabilities,82000.0,24000.0,151000.0,NaN
Deferred revenues,2804000.0,2052000.0,1284000.0,1207000.0
Other long-term liabilities,5330000.0,3546000.0,3330000.0,2691000.0
Total non-current liabilities,9731000.0,10843000.0,14221000.0,15532000.0
Total liabilities,36440000.0,30548000.0,28469000.0,26199000.0
Common stock,3000.0,1000.0,1000.0,0.0
Retained earnings,12885000.0,331000.0,-5399000.0,-6083000.0
Accumulated other comprehensive income,-361000.0,54000.0,363000.0,-36000.0
Total stockholders' equity,44704000.0,30189000.0,22225000.0,6618000.0
Total liabilities and stockholders' equity,82338000.0,62131000.0,52148000.0,34309000.0

It's time to acquire the normalization files via the Toolkit to be used to normalize the results.

In [3]:
Toolkit("TSLA").get_normalization_files()

Files are being saved to /Users/jeroenbouma/Downloads

With this information, by copying over each name as defined by OpenBB for the balance, income and cash flow statements as also defined above, the normalisation files can be filled. The result can be found within the `examples/normalisation` folder. Now it's time to convert each dataset in the right format.

In [4]:
from financialtoolkit.base import helpers

balance_sheets = helpers.combine_dataframes(
    ["TSLA", "GOOGL"],
    openbb.stocks.fa.balance("TSLA"),
    openbb.stocks.fa.balance("GOOGL"),
)
income_statements = helpers.combine_dataframes(
    ["TSLA", "GOOGL"], openbb.stocks.fa.income("TSLA"), openbb.stocks.fa.income("GOOGL")
)
cash_flow_statements = helpers.combine_dataframes(
    ["TSLA", "GOOGL"], openbb.stocks.fa.cash("TSLA"), openbb.stocks.fa.cash("GOOGL")
)

# The TTM column is dropped as it contains only a portion of this year
income_statements = income_statements.drop(columns=["ttm"])
cash_flow_statements = cash_flow_statements.drop(columns=["ttm"])

# Show the Results
balance_sheets

                                                   2022-12-31   2021-12-31  \
      Breakdown
GOOGL Cash and cash equivalents                    21879000.0   20945000.0
      Other short-term investments                 91883000.0  118704000.0
      Total cash                                  113762000.0  139649000.0
      Net receivables                              40258000.0   39304000.0
      Inventory                                     2670000.0    1170000.0
...                                                       ...          ...
TSLA  Common stock                                     3000.0       1000.0
      Retained earnings                            12885000.0     331000.0
      Accumulated other comprehensive income        -361000.0      54000.0
      Total stockholders' equity                   44704000.0   30189000.0
      Total liabilities and stockholders' equity   82338000.0   62131000.0

                                                   2020-12-31   2019-12-31
      Breakdown
GOOGL Cash and cash equivalents                    26465000.0   18498000.0
      Other short-term investments                110229000.0  101177000.0
      Total cash                                  136694000.0  119675000.0
      Net receivables                              30930000.0   25326000.0
      Inventory                                      728000.0     999000.0
...                                                       ...          ...
TSLA  Common stock                                     1000.0          0.0
      Retained earnings                            -5399000.0   -6083000.0
      Accumulated other comprehensive income         363000.0     -36000.0
      Total stockholders' equity                   22225000.0    6618000.0
      Total liabilities and stockholders' equity   52148000.0   34309000.0

[65 rows x 4 columns]

With this done, it's now time to initialize the Toolkit and start using the Financial Toolkit with these custom datasets. By looking at the Balance Sheet you can see that the column names have changed to the normalisation files.

**Note:** It is important to always ensure that dates go from left to right. For example this dataset starts at 2022 and ends at 2019. This should be reversed to accommodate shifting the DataFrames accordingly.

In [5]:
# initialize the Toolkit
companies = Toolkit(
    tickers=["TSLA", "GOOGL"],
    balance=balance_sheets,
    income=income_statements,
    cash=cash_flow_statements,
    format_location="normalisation",
    reverse_dates=True,
)  # Important when the dates are descending

# Show the Balance Sheet
companies.get_cash_flow_statement()

                                      2019-12-31   2020-12-31   2021-12-31  \
      Breakdown
GOOGL Net Income                      34343000.0   40269000.0   76033000.0
      Depreciation and Amortization   11781000.0   13697000.0   12441000.0
      Stock Based Compensation        10794000.0   12991000.0   15376000.0
      Change in Working Capital         819000.0    1827000.0   -1523000.0
      Accounts Receivables            -4340000.0   -6524000.0   -9095000.0
      Other Working Capital           30972000.0   42843000.0   67012000.0
      Other Non Cash Items             -592000.0    1267000.0    -213000.0
      Cash Flow from Operations       54520000.0   65124000.0   91652000.0
      Proprety, Plant and Equipment  -23548000.0  -22281000.0  -24640000.0
      Acquisitions                    -2515000.0    -738000.0   -2618000.0
      Purchases of Investments      -102247000.0 -143751000.0 -138034000.0
      Sales of Investments            98230000.0  133929000.0  129228000.0
      Other Investing Activities        589000.0      68000.0     541000.0
      Cash Flow from Investing       -29491000.0  -32773000.0  -35523000.0
      Debt Repayment                   -585000.0   -2100000.0  -21435000.0
      Other Financing Activities        220000.0    2800000.0     310000.0
      Cash Flow from Financing       -23209000.0  -24408000.0  -61362000.0
      Net Change in Cash               1797000.0    7967000.0   -5520000.0
      Cash Beginning of Period        16701000.0   18498000.0   26465000.0
      Cash End of Period              18498000.0   26465000.0   20945000.0
      Capital Expenditure            -23548000.0  -22281000.0  -24640000.0
      Free Cash Flow                  30972000.0   42843000.0   67012000.0
TSLA  Net Income                       -862000.0     690000.0    5519000.0
      Depreciation and Amortization    2154000.0    2322000.0    2911000.0
      Stock Based Compensation          898000.0    1734000.0    2121000.0
      Change in Working Capital        -349000.0     184000.0     518000.0
      Accounts Receivables             -367000.0    -652000.0    -130000.0
      Other Working Capital             968000.0    2701000.0    3483000.0
      Other Non Cash Items              477000.0     408000.0     245000.0
      Cash Flow from Operations        2405000.0    5943000.0   11497000.0
      Proprety, Plant and Equipment   -1437000.0   -3242000.0   -8014000.0
      Acquisitions                      -45000.0     -13000.0          0.0
      Purchases of Investments               NaN          NaN    -132000.0
      Sales of Investments                   NaN          NaN          NaN
      Other Investing Activities         46000.0     123000.0       6000.0
      Cash Flow from Investing        -1436000.0   -3132000.0   -7868000.0
      Debt Repayment                   -389000.0  -12201000.0  -14615000.0
      Other Financing Activities        222000.0    -225000.0    -178000.0
      Cash Flow from Financing         1529000.0    9973000.0   -5203000.0
      Net Change in Cash               2506000.0   13118000.0   -1757000.0
      Cash Beginning of Period         4277000.0    6783000.0   19901000.0
      Cash End of Period               6783000.0   19901000.0   18144000.0
      Capital Expenditure             -1437000.0   -3242000.0   -8014000.0
      Free Cash Flow                    968000.0    2701000.0    3483000.0
      Inventory                        -429000.0    -422000.0   -1709000.0
      Common Stock Issued               848000.0   12269000.0          0.0

                                     2022-12-31
      Breakdown
GOOGL Net Income                     59972000.0
      Depreciation and Amortization  15928000.0
      Stock Based Compensation       19362000.0
      Change in Working Capital      -2235000.0
      Accounts Receivables           -2317000.0
      Other Working Capital          60010000.0
      Other Non Cash Items            1030000.0
      Cash Flow from Operations      91495000.0
      Proprety, Plant and Equipment -31485000.0
      Acquisitions                   -6969000.0
      Purchases of Investments      -81405000.0
      Sales of Investments           97972000.0
      Other Investing Activities      1589000.0
      Cash Flow from Investing      -20298000.0
      Debt Repayment                -54068000.0
      Other Financing Activities        35000.0
      Cash Flow from Financing      -69757000.0
      Net Change in Cash               934000.0
      Cash Beginning of Period       20945000.0
      Cash End of Period             21879000.0
      Capital Expenditure           -31485000.0
      Free Cash Flow                 60010000.0
TSLA  Net Income                     12583000.0
      Depreciation and Amortization   3747000.0
      Stock Based Compensation        1560000.0
      Change in Working Capital      -3908000.0
      Accounts Receivables           -1124000.0
      Other Working Capital           7552000.0
      Other Non Cash Items             340000.0
      Cash Flow from Operations      14724000.0
      Proprety, Plant and Equipment  -7172000.0
      Acquisitions                          0.0
      Purchases of Investments       -5835000.0
      Sales of Investments              22000.0
      Other Investing Activities        76000.0
      Cash Flow from Investing      -11973000.0
      Debt Repayment                 -3866000.0
      Other Financing Activities      -202000.0
      Cash Flow from Financing       -3527000.0
      Net Change in Cash             -1220000.0
      Cash Beginning of Period       18144000.0
      Cash End of Period             16924000.0
      Capital Expenditure            -7172000.0
      Free Cash Flow                  7552000.0
      Inventory                      -6465000.0
      Common Stock Issued                   0.0

With this, it is now possible to do ratio calculations on these custom datasets. Let's have a look at the output of the extended Dupont model.

In [6]:
companies.models.get_extended_dupont_analysis()

                               2019-12-31  2020-12-31  2021-12-31  2022-12-31
GOOGL Interest Burden Ratio      0.906700    0.857369    0.867525    1.049265
      Tax Burden Ratio           0.955884    0.976834    0.965940    0.801315
      Operating Profit Margin    0.244815    0.263424    0.352178    0.252189
      Asset Turnover                  NaN    0.612995    0.759002    0.780741
      Equity Multiplier               NaN    1.404586    1.431704    1.426865
      Return on Equity                NaN    0.189954    0.320693    0.236213
TSLA  Interest Burden Ratio     -0.120301    1.727903    1.024121    1.008237
      Tax Burden Ratio         -10.775000    0.346038    0.849600    0.909702
      Operating Profit Margin   -0.027057    0.036593    0.117849    0.168410
      Asset Turnover                  NaN    0.729519    0.941958    1.127744
      Equity Multiplier               NaN    2.997504    2.180314    1.929005
      Return on Equity                NaN    0.047845    0.210593    0.336026

This can also be extended into the area of efficiency ratios.

In [7]:
companies.ratios.collect_efficiency_ratios()

                                                  2019-12-31  2020-12-31  \
GOOGL Days of Inventory Outstanding (DIO)                NaN    3.719699
      Days of Sales Outstanding (DSO)                    NaN   56.247678
      Operating Cycle (CC)                               NaN   59.967377
      Days of Accounts Payable Outstanding (DPO)         NaN   24.015425
      Cash Conversion Cycle (CCC)                        NaN   35.951952
      Receivables Turnover                               NaN    0.154103
      Inventory Turnover Ratio                           NaN   98.126230
      Accounts Payable Turnover Ratio                    NaN   15.198565
      SGA-to-Revenue Ratio                          0.173085    0.158870
      Fixed Asset Turnover                               NaN    1.358841
      Asset Turnover Ratio                               NaN    0.612995
      Operating Ratio                               0.778026    0.774148
TSLA  Days of Inventory Outstanding (DIO)                NaN   56.077752
      Days of Sales Outstanding (DSO)                    NaN   18.576389
      Operating Cycle (CC)                               NaN   74.654141
      Days of Accounts Payable Outstanding (DPO)         NaN   71.971212
      Cash Conversion Cycle (CCC)                        NaN    2.682929
      Receivables Turnover                               NaN    0.050894
      Inventory Turnover Ratio                           NaN    6.508820
      Accounts Payable Turnover Ratio                    NaN    5.071472
      SGA-to-Revenue Ratio                          0.107657    0.099727
      Fixed Asset Turnover                               NaN    1.324013
      Asset Turnover Ratio                               NaN    0.729519
      Operating Ratio                               0.996745    0.936771

                                                  2021-12-31  2022-12-31
GOOGL Days of Inventory Outstanding (DIO)           3.122301    5.552958
      Days of Sales Outstanding (DSO)              49.751026   51.337400
      Operating Cycle (CC)                         52.873327   56.890359
      Days of Accounts Payable Outstanding (DPO)   19.125330   16.145516
      Cash Conversion Cycle (CCC)                  33.747997   40.744843
      Receivables Turnover                          0.136304    0.140650
      Inventory Turnover Ratio                    116.900948   65.730729
      Accounts Payable Turnover Ratio              19.084638   22.606897
      SGA-to-Revenue Ratio                          0.141369    0.149525
      Fixed Asset Turnover                          1.628321    1.522285
      Asset Turnover Ratio                          0.759002    0.780741
      Operating Ratio                               0.694477    0.735387
TSLA  Days of Inventory Outstanding (DIO)          44.734441   55.994489
      Days of Sales Outstanding (DSO)              12.881435   10.899100
      Operating Cycle (CC)                         57.615876   66.893589
      Days of Accounts Payable Outstanding (DPO)   72.950991   76.120708
      Cash Conversion Cycle (CCC)                 -15.335115   -9.227119
      Receivables Turnover                          0.035292    0.029861
      Inventory Turnover Ratio                      8.159262    6.518499
      Accounts Payable Turnover Ratio               5.003359    4.795016
      SGA-to-Revenue Ratio                          0.083923    0.048440
      Fixed Asset Turnover                          1.780391    2.131063
      Asset Turnover Ratio                          0.941958    1.127744
      Operating Ratio                               0.879308    0.830203

And lastly, the historical data can also be viewed.

In [8]:
companies.get_historical_data()

             Adj Close                   Close                    High  \
                 GOOGL        TSLA       GOOGL        TSLA       GOOGL
Date
2013-05-24   21.854855    6.472000   21.854855    6.472000   21.992493
2013-05-28   22.053804    7.355333   22.053804    7.355333   22.325827
2013-05-29   21.729479    6.975333   21.729479    6.975333   21.971722
2013-05-30   21.790791    6.996667   21.790791    6.996667   21.994493
2013-05-31   21.802301    6.517333   21.802301    6.517333   21.946947
...                ...         ...         ...         ...         ...
2023-05-16  119.510002  166.520004  119.510002  166.520004  120.750000
2023-05-17  120.839996  173.860001  120.839996  173.860001  121.669998
2023-05-18  122.830002  176.889999  122.830002  176.889999  123.309998
2023-05-19  122.760002  180.139999  122.760002  180.139999  125.970001
2023-05-22  125.264999  182.559601  125.264999  182.559601  126.430000

                               Low                    Open              \
                  TSLA       GOOGL        TSLA       GOOGL        TSLA
Date
2013-05-24    6.530000   21.797047    6.133333   21.903402    6.173333
2013-05-28    7.383333   22.032032    6.686667   22.109610    6.770000
2013-05-29    7.660000   21.628880    6.600000   21.914665    7.570000
2013-05-30    7.302667   21.681932    6.746667   21.769770    6.830667
2013-05-31    7.096000   21.709709    6.515333   21.724726    7.084000
...                ...         ...         ...         ...         ...
2023-05-16  169.520004  116.430000  164.350006  116.489998  165.649994
2023-05-17  174.500000  118.889999  167.190002  119.610001  168.410004
2023-05-18  177.059998  120.830002  172.449997  120.949997  174.220001
2023-05-19  181.949997  122.150002  176.309998  123.550003  177.169998
2023-05-22  185.399994  122.917503  180.110001  122.940002  180.699997

              Volume
               GOOGL       TSLA
Date
2013-05-24  91780128  241863000
2013-05-28  90209700  295378500
2013-05-29  80455464  376492500
2013-05-30  84743172  242005500
2013-05-31  78697224  227580000
...              ...        ...
2023-05-16  45035600   98288800
2023-05-17  33323600  125473600
2023-05-18  35234200  109520300
2023-05-19  41330300  136024200
2023-05-22  10251529   30446005

[2516 rows x 12 columns]

Note that it is possible that your dataset doesn't cover all financial statement items if your normalization files are incomplete. This will become apparent when some ratios can not be calculated.

In [14]:
# Missing column returns an empty series
display(companies.ratios.get_debt_to_assets_ratio())

# Missing column skips the ratio in the total overview
display(companies.ratios.collect_profitability_ratios())

There is an index name missing in the provided financial statements. This is 'Total Debt'. This is required for the function (get_debt_to_assets_ratio) to run. Please fill this column to be able to calculate the ratios.

Series([], dtype: float64)

There is an index name missing in the provided financial statements. This is 'Depreciation and Amortization'. This is required for the function (get_interest_coverage_ratio) to run. Please fill this column to be able to calculate the ratios.
There is an index name missing in the provided financial statements. This is 'Dividends Paid'. This is required for the function (get_return_on_invested_capital) to run. Please fill this column to be able to calculate the ratios.

                                                   2019-12-31  2020-12-31  \
GOOGL Gross Margin                                   0.555805    0.535784
      Operating Margin                               0.221974    0.225852
      Net Profit Margin                              0.212181    0.220619
      Income Before Tax Profit Margin                0.244815    0.263424
      Effective Tax Rate                             0.133300    0.162493
      Return on Assets (ROA)                         0.124472    0.125992
      Return on Equity (ROE)                              NaN    0.189954
      Return on Capital Employed (ROCE)              0.172202    0.183487
      Return on Tangible Assets                      0.172177    0.182131
      Income Quality Ratio                           1.587514    1.617224
      Net Income per EBT                             0.866700    0.837507
      Free Cash Flow to Operating Cash Flow Ratio    0.568085    0.657868
      EBT to EBIT Ratio                              0.997483    0.997200
      EBIT to Revenue                                0.245433    0.264164
TSLA  Gross Margin                                   0.165555    0.210236
      Operating Margin                               0.003255    0.063229
      Net Profit Margin                             -0.035072    0.021880
      Income Before Tax Profit Margin               -0.027057    0.036593
      Effective Tax Rate                            -0.165414    0.253033
      Return on Assets (ROA)                        -0.025125    0.013232
      Return on Equity (ROE)                              NaN    0.047845
      Return on Capital Employed (ROCE)             -0.002834    0.045646
      Return on Tangible Assets                     -0.110925    0.029530
      Income Quality Ratio                          -2.790023    8.613043
      Net Income per EBT                             1.146277    0.702648
      Free Cash Flow to Operating Cash Flow Ratio    0.402495    0.454484
      EBT to EBIT Ratio                             11.223881    0.567630
      EBIT to Revenue                               -0.002726    0.054858

                                                   2021-12-31  2022-12-31
GOOGL Gross Margin                                   0.569398    0.553794
      Operating Margin                               0.305523    0.264613
      Net Profit Margin                              0.295117    0.212038
      Income Before Tax Profit Margin                0.352178    0.252189
      Effective Tax Rate                             0.162023    0.159208
      Return on Assets (ROA)                         0.211633    0.164188
      Return on Equity (ROE)                         0.320693    0.236213
      Return on Capital Employed (ROCE)              0.308731    0.242209
      Return on Tangible Assets                      0.303867    0.236054
      Income Quality Ratio                           1.205424    1.525629
      Net Income per EBT                             0.837977    0.840792
      Free Cash Flow to Operating Cash Flow Ratio    0.731157    0.655883
      EBT to EBIT Ratio                              0.996201    0.995020
      EBIT to Revenue                                0.353521    0.253451
TSLA  Gross Margin                                   0.252792    0.255984
      Operating Margin                               0.120692    0.169797
      Net Profit Margin                              0.102540    0.154465
      Income Before Tax Profit Margin                0.117849    0.168410
      Effective Tax Rate                             0.110200    0.082513
      Return on Assets (ROA)                         0.088828    0.152821
      Return on Equity (ROE)                         0.210593    0.336026
      Return on Capital Employed (ROCE)              0.155306    0.249978
      Return on Tangible Assets                      0.184792    0.277740
      Income Quality Ratio                           2.083167    1.170150
      Net Income per EBT                             0.887584    0.917463
      Free Cash Flow to Operating Cash Flow Ratio    0.302949    0.512904
      EBT to EBIT Ratio                              0.943694    0.986265
      EBIT to Revenue                                0.122420    0.170705